#!/usr/bin/env python3
"""yard-plugin-airflow: Airflow DAG plugin for yard CLI.

Implements the JSON-over-stdio plugin protocol in Python, mirroring the Rust
SDK's PluginServer::run() lifecycle. Generates Airflow DAG Python files from
yard DAG configuration, validates config, and manages DAG file lifecycle on S3.

Protocol: handshake JSON on stdout -> read request from stdin -> write response
on stdout -> exit. All logging goes to stderr via the logging module. stdout is
reserved exclusively for protocol JSON.
"""

import json
import logging
import re
import sys

from jinja2 import Environment

# ---------------------------------------------------------------------------
# Logging: all output goes to stderr. stdout is the protocol channel.
# ---------------------------------------------------------------------------
logging.basicConfig(
    stream=sys.stderr,
    level=logging.INFO,
    format="%(levelname)s: %(message)s",
)
log = logging.getLogger("yard-plugin-airflow")

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
PLUGIN_NAME = "yard-plugin-airflow"
PLUGIN_VERSION = "0.1.0"
PROTOCOL_VERSION = 1

# ---------------------------------------------------------------------------
# Version-aware imports (D-07): matches reference version.rs scope exactly.
# ---------------------------------------------------------------------------
VERSION_IMPORTS = {
    2: {
        "class_name": "Dataset",
        "class_import": "from airflow.datasets import Dataset",
        "bash_op_import": "from airflow.operators.bash import BashOperator",
        "empty_op_import": "from airflow.operators.empty import EmptyOperator",
    },
    3: {
        "class_name": "Asset",
        "class_import": "from airflow.sdk import Asset",
        "bash_op_import": "from airflow.providers.standard.operators.bash import BashOperator",
        "empty_op_import": "from airflow.providers.standard.operators.empty import EmptyOperator",
    },
}

# ---------------------------------------------------------------------------
# Version banners (ported from version.rs VERSION_BANNER / VERSION_BANNER_V3)
# ---------------------------------------------------------------------------
VERSION_BANNERS = {
    2: (
        "# Airflow version contract:\n"
        "#   - apache-airflow >= 2.9\n"
        "#   - apache-airflow-providers-amazon >= 8.13.0\n"
        "#   - aiobotocore >= 2.1.1\n"
        "#   - Triggerer process required\n"
    ),
    3: (
        "# Airflow version contract:\n"
        "#   - apache-airflow >= 3.0\n"
        "#   - apache-airflow-providers-amazon >= 9.0.0\n"
        "#   - apache-airflow-providers-standard\n"
    ),
}

# ---------------------------------------------------------------------------
# DAG template (ported from airflow_dag.py.tera -- Jinja2 variable-only)
# ---------------------------------------------------------------------------
DAG_TEMPLATE = """\
# Generated by YARD for DAG: {{ dag_name }}
{{ trigger_header_block }}{{ required_connections_block }}
from datetime import datetime

from airflow import DAG
{{ imports_block }}

default_args = {{ default_args }}

with DAG(
    dag_id="{{ dag_name }}",
    default_args=default_args,
    schedule={{ schedule }},
{{ max_active_runs_block }}    start_date=datetime(2024, 1, 1),
    catchup=False,
) as dag:
{{ tasks_block }}

{{ deps_block }}
"""

# ---------------------------------------------------------------------------
# Helper functions (ported from helpers.rs)
# ---------------------------------------------------------------------------

_SANITIZE_RE = re.compile(r"[^A-Za-z0-9_]")


def sanitize_identifier(s):
    """Sanitize a string into a Python identifier fragment.

    Keep [A-Za-z0-9_], replace everything else with _, prepend _ if the first
    char is a digit. Return '_' if the result would be empty.
    """
    out = _SANITIZE_RE.sub("_", s)
    if not out:
        return "_"
    if out[0].isdigit():
        out = "_" + out
    return out


def python_var_name(task_id):
    """Convert a task id to a Python variable name: t_{sanitized}."""
    return "t_" + sanitize_identifier(task_id)


def python_string_literal(s):
    """Return a Python string literal using json.dumps (JSON strings are valid Python literals)."""
    return json.dumps(s)


# ---------------------------------------------------------------------------
# Rendering helpers (ported from generation.rs)
# ---------------------------------------------------------------------------


def render_default_args(config):
    """Render the default_args dict for the DAG constructor.

    Only includes fields that are explicitly set (owner, retries).
    Returns '{}' when no default args are configured.
    """
    entries = []

    # Check default_args sub-dict first, then top-level config
    default_args = config.get("default_args", {})
    owner = default_args.get("owner") or config.get("owner")
    retries = default_args.get("retries")
    if retries is None:
        retries = config.get("retries")

    if owner:
        entries.append('    "owner": {},'.format(python_string_literal(owner)))
    if retries is not None:
        entries.append('    "retries": {},'.format(retries))

    if not entries:
        return "{}"
    return "{{\n{}\n}}".format("\n".join(entries))


def render_task(task_id, task_config, version):
    """Render a single task assignment inside the 'with DAG(...)' block.

    Supports 'bash' and 'glue' task types. Raises ValueError for unsupported types.
    """
    var = python_var_name(task_id)
    tid = python_string_literal(task_id)
    vi = VERSION_IMPORTS[version]

    task_type = task_config.get("task_type", "")

    if task_type == "bash":
        cmd = task_config.get("command", "")
        return (
            "    {var} = BashOperator(\n"
            "        task_id={tid},\n"
            "        bash_command={cmd},\n"
            "    )".format(
                var=var,
                tid=tid,
                cmd=python_string_literal(cmd),
            )
        )
    elif task_type == "glue":
        job_name = task_config.get("job_name", task_id)
        script_location = task_config.get("script_location", "")
        iam_role_arn = task_config.get("iam_role_arn", "")
        aws_conn_id = task_config.get("aws_conn_id", "aws_default")
        return (
            "    {var} = GlueJobOperator(\n"
            "        task_id={tid},\n"
            "        job_name={jn},\n"
            "        script_location={sl},\n"
            "        iam_role_arn={ir},\n"
            "        aws_conn_id={cn},\n"
            "    )".format(
                var=var,
                tid=tid,
                jn=python_string_literal(job_name),
                sl=python_string_literal(script_location),
                ir=python_string_literal(iam_role_arn),
                cn=python_string_literal(aws_conn_id),
            )
        )
    else:
        raise ValueError(
            "task '{}': task_type '{}' is not supported in Airflow codegen yet".format(
                task_id, task_type
            )
        )


def render_dag(job_name, job_config):
    """Main codegen entry point: render a complete Airflow DAG Python file.

    For Plan 1, supports schedule-only DAGs. Trigger support is added in Plan 2.
    """
    # D-06: default airflow version is 3
    version = job_config.get("airflow_version", 3)
    vi = VERSION_IMPORTS[version]

    schedule = job_config.get("schedule")
    tasks = job_config.get("tasks", [])

    # Determine which operator imports are needed
    needs_bash = False
    needs_glue = False
    for task in tasks:
        tt = task.get("task_type", "")
        if tt == "bash":
            needs_bash = True
        elif tt == "glue":
            needs_glue = True

    import_lines = []
    if needs_bash:
        import_lines.append(vi["bash_op_import"])
    if needs_glue:
        import_lines.append(
            "from airflow.providers.amazon.aws.operators.glue import GlueJobOperator"
        )
    imports_block = "\n".join(import_lines)

    # Render default_args
    default_args = render_default_args(job_config)

    # Schedule expression
    if schedule is not None:
        schedule_expr = python_string_literal(schedule)
    else:
        schedule_expr = "None"

    # max_active_runs -- empty for schedule-only DAGs (plan 1)
    max_active_runs = job_config.get("max_active_runs")
    if max_active_runs is not None:
        max_active_runs_block = "    max_active_runs={},\n".format(max_active_runs)
    else:
        max_active_runs_block = ""

    # Render tasks
    task_lines = []
    for task in tasks:
        tid = task.get("task_id", "")
        task_lines.append(render_task(tid, task, version))
    tasks_block = "\n".join(task_lines)

    # Dependency wiring
    dep_lines = []
    for task in tasks:
        tid = task.get("task_id", "")
        depends_on = task.get("depends_on", [])
        for upstream in depends_on:
            dep_lines.append("{} >> {}".format(python_var_name(upstream), python_var_name(tid)))

    if dep_lines:
        deps_block = "\n".join(dep_lines)
    else:
        deps_block = "# No task dependencies"

    # Trigger header block -- empty for schedule-only DAGs (Plan 1)
    trigger_header_block = ""

    # Required connections block -- empty for Plan 1
    required_connections_block = ""

    # Render via Jinja2
    env = Environment()
    template = env.from_string(DAG_TEMPLATE)
    return template.render(
        dag_name=job_name,
        trigger_header_block=trigger_header_block,
        required_connections_block=required_connections_block,
        imports_block=imports_block,
        default_args=default_args,
        schedule=schedule_expr,
        max_active_runs_block=max_active_runs_block,
        tasks_block=tasks_block,
        deps_block=deps_block,
    )


# ---------------------------------------------------------------------------
# Protocol handlers
# ---------------------------------------------------------------------------


def handle_validate(job_name, job_config):
    """Validate DAG configuration. Returns {'errors': [...]}."""
    errors = []

    # Rule: dags_bucket is required (D-10)
    dags_bucket = job_config.get("dags_bucket", "")
    if not dags_bucket:
        errors.append({
            "field": "dags_bucket",
            "message": "dags_bucket is required",
            "severity": "error",
        })

    # Rule: trigger and schedule mutual exclusion
    has_schedule = bool(job_config.get("schedule"))
    has_trigger = job_config.get("trigger") is not None
    if has_schedule and has_trigger:
        trigger = job_config["trigger"]
        # A schedule-type trigger inside trigger: is allowed with schedule field
        if not (isinstance(trigger, dict) and "schedule" in trigger):
            errors.append({
                "field": "trigger",
                "message": "trigger and schedule are mutually exclusive",
                "severity": "error",
            })

    # Rule: airflow_version must be 2 or 3 if present
    av = job_config.get("airflow_version")
    if av is not None and av not in (2, 3):
        errors.append({
            "field": "airflow_version",
            "message": "airflow_version must be 2 or 3",
            "severity": "error",
        })

    # Rule: connection_id syntax validation (D-11)
    tasks = job_config.get("tasks", [])
    for task in tasks:
        conn_id = task.get("aws_conn_id") or task.get("connection_id")
        if conn_id is not None and (not isinstance(conn_id, str) or not conn_id.strip()):
            errors.append({
                "field": "connection_id",
                "message": "connection_id must be a non-empty string",
                "severity": "error",
            })

    return {"errors": errors}


def handle_codegen(job_name, job_config):
    """Generate an Airflow DAG Python file. Returns {'script': '...'}."""
    script = render_dag(job_name, job_config)
    return {"script": script}


def handle_deploy(job_name, job_config, artifact):
    """Deploy a DAG file to S3. Stub for Plan 3."""
    raise NotImplementedError("deploy not yet implemented")


def handle_destroy(job_name, resources):
    """Destroy a DAG file from S3. Stub for Plan 3."""
    raise NotImplementedError("destroy not yet implemented")


def handle_verify(job_name, resources):
    """Verify a DAG file exists on S3. Stub for Plan 3."""
    raise NotImplementedError("verify not yet implemented")


def handle_schema():
    """Return config field descriptors for the Airflow plugin."""
    return {
        "fields": [
            {
                "name": "dags_bucket",
                "field_type": "string",
                "required": True,
                "description": "S3 bucket for DAG file uploads",
            },
            {
                "name": "schedule",
                "field_type": "string",
                "required": False,
                "description": "Cron schedule expression",
            },
            {
                "name": "airflow_version",
                "field_type": "integer",
                "required": False,
                "description": "Airflow major version: 2 or 3, default 3",
            },
            {
                "name": "owner",
                "field_type": "string",
                "required": False,
                "description": "DAG owner",
            },
            {
                "name": "retries",
                "field_type": "integer",
                "required": False,
                "description": "Default task retries",
            },
            {
                "name": "max_active_runs",
                "field_type": "integer",
                "required": False,
                "description": "Maximum concurrent DAG runs",
            },
        ],
        "supported_source_types": None,
        "supported_sink_types": None,
    }


# ---------------------------------------------------------------------------
# Dispatch
# ---------------------------------------------------------------------------


def dispatch(request):
    """Route request to the appropriate handler by operation."""
    op = request.get("operation")
    if op == "validate":
        return handle_validate(request["job_name"], request["job_config"])
    elif op == "codegen":
        return handle_codegen(request["job_name"], request["job_config"])
    elif op == "deploy":
        return handle_deploy(
            request["job_name"], request["job_config"], request["artifact"]
        )
    elif op == "destroy":
        return handle_destroy(request["job_name"], request["resources"])
    elif op == "verify":
        return handle_verify(request["job_name"], request["resources"])
    elif op == "schema":
        return handle_schema()
    else:
        raise ValueError("unknown operation: {}".format(op))


# ---------------------------------------------------------------------------
# Protocol entry point (mirrors PluginServer::run from server.rs)
# ---------------------------------------------------------------------------


def main():
    """Protocol lifecycle: handshake -> read request -> dispatch -> respond -> exit."""
    try:
        # Step 1: Write handshake to stdout
        handshake = {
            "protocol_version": PROTOCOL_VERSION,
            "name": PLUGIN_NAME,
            "version": PLUGIN_VERSION,
            "capabilities": [
                "validate",
                "codegen",
                "deploy",
                "destroy",
                "verify",
                "schema",
            ],
        }
        sys.stdout.write(json.dumps(handshake) + "\n")
        sys.stdout.flush()

        # Step 2: Read request from stdin
        line = sys.stdin.readline()
        if not line.strip():
            log.error("no request received on stdin")
            sys.exit(1)

        request = json.loads(line.strip())

        # Step 3: Dispatch and write response
        response = dispatch(request)
        sys.stdout.write(json.dumps(response) + "\n")
        sys.stdout.flush()
        sys.exit(0)

    except Exception as exc:
        log.error("%s", exc)
        sys.exit(1)


if __name__ == "__main__":
    main()
