#!/usr/bin/env python3
"""yard-plugin-airflow: Airflow DAG plugin for yard CLI.

Implements the JSON-over-stdio plugin protocol in Python, mirroring the Rust
SDK's PluginServer::run() lifecycle. Generates Airflow DAG Python files from
yard DAG configuration, validates config, and manages DAG file lifecycle on S3.

Protocol: handshake JSON on stdout -> read request from stdin -> write response
on stdout -> exit. All logging goes to stderr via the logging module. stdout is
reserved exclusively for protocol JSON.
"""

import json
import logging
import re
import sys

from jinja2 import Environment

# ---------------------------------------------------------------------------
# Logging: all output goes to stderr. stdout is the protocol channel.
# ---------------------------------------------------------------------------
logging.basicConfig(
    stream=sys.stderr,
    level=logging.INFO,
    format="%(levelname)s: %(message)s",
)
log = logging.getLogger("yard-plugin-airflow")

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
PLUGIN_NAME = "yard-plugin-airflow"
PLUGIN_VERSION = "0.1.0"
PROTOCOL_VERSION = 1

# ---------------------------------------------------------------------------
# Version-aware imports (D-07): matches reference version.rs scope exactly.
# ---------------------------------------------------------------------------
VERSION_IMPORTS = {
    2: {
        "class_name": "Dataset",
        "class_import": "from airflow.datasets import Dataset",
        "bash_op_import": "from airflow.operators.bash import BashOperator",
        "empty_op_import": "from airflow.operators.empty import EmptyOperator",
    },
    3: {
        "class_name": "Asset",
        "class_import": "from airflow.sdk import Asset",
        "bash_op_import": "from airflow.providers.standard.operators.bash import BashOperator",
        "empty_op_import": "from airflow.providers.standard.operators.empty import EmptyOperator",
    },
}

# ---------------------------------------------------------------------------
# Version banners (ported from version.rs VERSION_BANNER / VERSION_BANNER_V3)
# ---------------------------------------------------------------------------
VERSION_BANNERS = {
    2: (
        "# Airflow version contract:\n"
        "#   - apache-airflow >= 2.9\n"
        "#   - apache-airflow-providers-amazon >= 8.13.0\n"
        "#   - aiobotocore >= 2.1.1\n"
        "#   - Triggerer process required\n"
    ),
    3: (
        "# Airflow version contract:\n"
        "#   - apache-airflow >= 3.0\n"
        "#   - apache-airflow-providers-amazon >= 9.0.0\n"
        "#   - apache-airflow-providers-standard\n"
    ),
}

# ---------------------------------------------------------------------------
# Trigger header helpers (ported from triggers.rs D-13 per-source caveats)
# ---------------------------------------------------------------------------


def dataset_header(uri, version):
    """D-13: Dataset/Asset backfill caveat header."""
    cls = VERSION_IMPORTS[version]["class_name"]
    return (
        "# Trigger: {cls} ({uri})\n"
        "#\n"
        "# Backfill caveat: {cls}s have no logical_date — historical re-runs do NOT\n"
        "# replay missed {cls} events. Use API-trigger replay (see DOC-04) to backfill\n"
        "# this DAG against synthetic dag_run.conf payloads.\n"
    ).format(cls=cls, uri=uri)


def s3_header(bucket, key=None, prefix=None):
    """D-13: S3 backfill caveat header."""
    if key:
        target = "key={}".format(key)
    elif prefix:
        target = "prefix={}".format(prefix)
    else:
        target = ""
    return (
        "# Trigger: S3 (bucket={bucket}, {target})\n"
        "#\n"
        "# Backfill caveat: deferrable sensor re-pokes against current S3 state —\n"
        "# original landed object is not replayable from event history.\n"
    ).format(bucket=bucket, target=target)


def sqs_header(queue_url):
    """D-13: SQS backfill caveat header."""
    return (
        "# Trigger: SQS (queue_url={queue_url})\n"
        "#\n"
        "# Backfill caveat: SqsSensor drains the real queue — backfill is destructive\n"
        "# and is not safe to run against a live queue.\n"
    ).format(queue_url=queue_url)


# ---------------------------------------------------------------------------
# DAG template (ported from airflow_dag.py.tera -- Jinja2 variable-only)
# ---------------------------------------------------------------------------
DAG_TEMPLATE = """\
# Generated by YARD for DAG: {{ dag_name }}
{{ trigger_header_block }}{{ required_connections_block }}
from datetime import datetime

from airflow import DAG
{{ imports_block }}

default_args = {{ default_args }}

with DAG(
    dag_id="{{ dag_name }}",
    default_args=default_args,
    schedule={{ schedule }},
{{ max_active_runs_block }}    start_date=datetime(2024, 1, 1),
    catchup=False,
) as dag:
{{ tasks_block }}

{{ deps_block }}
"""

# ---------------------------------------------------------------------------
# Helper functions (ported from helpers.rs)
# ---------------------------------------------------------------------------

_SANITIZE_RE = re.compile(r"[^A-Za-z0-9_]")


def sanitize_identifier(s):
    """Sanitize a string into a Python identifier fragment.

    Keep [A-Za-z0-9_], replace everything else with _, prepend _ if the first
    char is a digit. Return '_' if the result would be empty.
    """
    out = _SANITIZE_RE.sub("_", s)
    if not out:
        return "_"
    if out[0].isdigit():
        out = "_" + out
    return out


def python_var_name(task_id):
    """Convert a task id to a Python variable name: t_{sanitized}."""
    return "t_" + sanitize_identifier(task_id)


def python_string_literal(s):
    """Return a Python string literal using json.dumps (JSON strings are valid Python literals)."""
    return json.dumps(s)


# ---------------------------------------------------------------------------
# Rendering helpers (ported from generation.rs)
# ---------------------------------------------------------------------------


def render_default_args(config):
    """Render the default_args dict for the DAG constructor.

    Only includes fields that are explicitly set (owner, retries).
    Returns '{}' when no default args are configured.
    """
    entries = []

    # Check default_args sub-dict first, then top-level config
    default_args = config.get("default_args", {})
    owner = default_args.get("owner") or config.get("owner")
    retries = default_args.get("retries")
    if retries is None:
        retries = config.get("retries")

    if owner:
        entries.append('    "owner": {},'.format(python_string_literal(owner)))
    if retries is not None:
        entries.append('    "retries": {},'.format(retries))

    if not entries:
        return "{}"
    return "{{\n{}\n}}".format("\n".join(entries))


def render_outlets(task_config, version):
    """Render outlets=[Class(uri)] kwarg fragment for tasks with publishes.

    Returns a formatted line (with leading 8-space indent and trailing newline)
    when the task has a 'publishes' list, or empty string otherwise.
    """
    publishes = task_config.get("publishes", [])
    if not publishes:
        return ""
    vi = VERSION_IMPORTS[version]
    outlets = ", ".join(
        "{}({})".format(vi["class_name"], python_string_literal(uri))
        for uri in publishes
    )
    return "        outlets=[{}],\n".format(outlets)


def render_task(task_id, task_config, version):
    """Render a single task assignment inside the 'with DAG(...)' block.

    Supports 'bash' and 'glue' task types. Raises ValueError for unsupported types.
    """
    var = python_var_name(task_id)
    tid = python_string_literal(task_id)
    vi = VERSION_IMPORTS[version]
    outlets_line = render_outlets(task_config, version)

    task_type = task_config.get("task_type", "")

    if task_type == "bash":
        cmd = task_config.get("command", "")
        return (
            "    {var} = BashOperator(\n"
            "        task_id={tid},\n"
            "        bash_command={cmd},\n"
            "{outlets}"
            "    )".format(
                var=var,
                tid=tid,
                cmd=python_string_literal(cmd),
                outlets=outlets_line,
            )
        )
    elif task_type == "glue":
        job_name = task_config.get("job_name", task_id)
        script_location = task_config.get("script_location", "")
        iam_role_arn = task_config.get("iam_role_arn", "")
        aws_conn_id = task_config.get("aws_conn_id", "aws_default")
        return (
            "    {var} = GlueJobOperator(\n"
            "        task_id={tid},\n"
            "        job_name={jn},\n"
            "        script_location={sl},\n"
            "        iam_role_arn={ir},\n"
            "        aws_conn_id={cn},\n"
            "{outlets}"
            "    )".format(
                var=var,
                tid=tid,
                jn=python_string_literal(job_name),
                sl=python_string_literal(script_location),
                ir=python_string_literal(iam_role_arn),
                cn=python_string_literal(aws_conn_id),
                outlets=outlets_line,
            )
        )
    else:
        raise ValueError(
            "task '{}': task_type '{}' is not supported in Airflow codegen yet".format(
                task_id, task_type
            )
        )


# ---------------------------------------------------------------------------
# Trigger rendering (ported from triggers.rs -- D-03 single entry point)
# ---------------------------------------------------------------------------


def render_single_trigger(source, default_aws_conn_id, roots, version):
    """Render a single trigger source into codegen fragments.

    Handles: schedule, dataset, s3, sqs, api source types.
    Returns dict with keys: schedule_expr, sensor_tasks, sensor_deps,
    extra_imports, max_active_runs, header_docstring.
    """
    vi = VERSION_IMPORTS[version]

    if "schedule" in source:
        return {
            "schedule_expr": python_string_literal(source["schedule"]),
            "sensor_tasks": [],
            "sensor_deps": [],
            "extra_imports": [],
            "max_active_runs": None,
            "header_docstring": "",
        }

    if "dataset" in source:
        uri = source["dataset"]["uri"]
        return {
            "schedule_expr": "[{}({})]".format(
                vi["class_name"], python_string_literal(uri)
            ),
            "sensor_tasks": [],
            "sensor_deps": [],
            "extra_imports": [vi["class_import"]],
            "max_active_runs": None,
            "header_docstring": dataset_header(uri, version),
        }

    if "s3" in source:
        s3 = source["s3"]
        bucket = s3["bucket"]
        poke = s3.get("poke_interval", 60)
        timeout = s3.get("timeout", 86400)
        deferrable = s3.get("deferrable", True)
        # S3-04 precedence (D-12): per-trigger > DAG-level > "aws_default"
        conn = s3.get("aws_conn_id") or default_aws_conn_id or "aws_default"

        bucket_key_value = s3.get("key") or s3.get("prefix") or ""

        sensor_lines = [
            "    _yard_wait_s3 = S3KeySensor(",
            '        task_id="_yard_wait_s3",',
            "        bucket_name={},".format(python_string_literal(bucket)),
            "        bucket_key={},".format(python_string_literal(bucket_key_value)),
            "        poke_interval={},".format(poke),
            "        timeout={},".format(timeout),
            "        deferrable={},".format("True" if deferrable else "False"),
            "        aws_conn_id={},".format(python_string_literal(conn)),
            "    )",
        ]
        sensor = "\n".join(sensor_lines)

        deps = [
            "_yard_wait_s3 >> {}".format(python_var_name(r)) for r in roots
        ]

        return {
            "schedule_expr": "None",
            "sensor_tasks": [sensor],
            "sensor_deps": deps,
            "extra_imports": [
                "from airflow.providers.amazon.aws.sensors.s3 import S3KeySensor"
            ],
            "max_active_runs": None,
            "header_docstring": s3_header(
                bucket, s3.get("key"), s3.get("prefix")
            ),
        }

    if "sqs" in source:
        sqs = source["sqs"]
        queue_url = sqs["queue_url"]
        wait = sqs.get("wait_time_seconds", 20)
        max_msgs = sqs.get("max_messages", 5)
        del_on_recv = sqs.get("delete_message_on_reception", True)
        # SQS: DAG-level only (no per-trigger override), fall back to "aws_default"
        conn = default_aws_conn_id or "aws_default"

        sensor_lines = [
            "    _yard_wait_sqs = SqsSensor(",
            '        task_id="_yard_wait_sqs",',
            "        sqs_queue={},".format(python_string_literal(queue_url)),
            "        wait_time_seconds={},".format(wait),
            "        max_messages={},".format(max_msgs),
            "        delete_message_on_reception={},".format(
                "True" if del_on_recv else "False"
            ),
            "        deferrable=True,",
            "        aws_conn_id={},".format(python_string_literal(conn)),
            "    )",
        ]
        sensor = "\n".join(sensor_lines)

        deps = [
            "_yard_wait_sqs >> {}".format(python_var_name(r)) for r in roots
        ]

        return {
            "schedule_expr": "None",
            "sensor_tasks": [sensor],
            "sensor_deps": deps,
            "extra_imports": [
                "from airflow.providers.amazon.aws.sensors.sqs import SqsSensor"
            ],
            "max_active_runs": None,
            "header_docstring": sqs_header(queue_url),
        }

    if "api" in source:
        api = source["api"]
        header = "# Trigger: API (manual / external invocation)\n"
        desc = api.get("description")
        if desc:
            header += "# {}\n".format(desc)
        header += "#\n"
        header += (
            "# This DAG is triggered manually via Airflow's REST API or CLI.\n"
        )
        header += (
            "# yard does NOT manage Airflow REST auth — configure JWT, Basic,\n"
        )
        header += "# or IAM SigV4 credentials in your Airflow deployment.\n"
        header += "#\n"
        header += "# Invoke via REST:\n"
        header += (
            '#   curl -X POST "$AIRFLOW_URL/api/v1/dags/<dag_id>/dagRuns" \\\n'
        )
        header += '#        -u "$AIRFLOW_USER:$AIRFLOW_PASS" \\\n'
        header += '#        -H "Content-Type: application/json" \\\n'
        header += "#        -d '{\"conf\": {\"key\": \"value\"}}'\n"
        header += "#\n"
        header += "# Invoke via CLI:\n"
        header += (
            "#   airflow dags trigger <dag_id>"
            " --conf '{\"key\": \"value\"}'\n"
        )

        payload_schema = api.get("payload_schema")
        if isinstance(payload_schema, dict) and payload_schema:
            header += "#\n"
            header += (
                "# Expected payload fields"
                " (doc-only — no runtime enforcement in v1.6):\n"
            )
            for field in sorted(payload_schema.keys()):
                header += "#   {}: {}\n".format(field, payload_schema[field])

        return {
            "schedule_expr": "None",
            "sensor_tasks": [],
            "sensor_deps": [],
            "extra_imports": [],
            "max_active_runs": None,
            "header_docstring": header,
        }

    # Unknown source type
    return {
        "schedule_expr": "None",
        "sensor_tasks": [],
        "sensor_deps": [],
        "extra_imports": [],
        "max_active_runs": None,
        "header_docstring": "# Trigger: unknown source type\n",
    }


def _source_kind(item):
    """Return the source kind key for sorting (D-07: alphabetical)."""
    for key in ("api", "dataset", "s3", "schedule", "sqs"):
        if key in item:
            return key
    return ""


def render_composite_trigger(trigger, default_aws_conn_id, roots, version):
    """Render a composite trigger (all/any) into codegen fragments.

    DS-02/DS-03: homogeneous datasets produce alpha-sorted chain at schedule level.
    DS-04/D-11: heterogeneous-all splits datasets to schedule, non-datasets to sensors.
    D-10: _yard_join EmptyOperator only when 2+ sensor tasks.
    """
    vi = VERSION_IMPORTS[version]

    if "all" in trigger:
        items = trigger["all"]
        separator = " & "
    elif "any" in trigger:
        items = trigger["any"]
        separator = " | "
    else:
        return {
            "schedule_expr": "None",
            "sensor_tasks": [],
            "sensor_deps": [],
            "extra_imports": [],
            "max_active_runs": None,
            "header_docstring": "",
        }

    # DS-02/DS-03: homogeneous datasets — alpha-sort URIs and join
    all_datasets = all("dataset" in item for item in items)

    if all_datasets:
        uris = sorted(item["dataset"]["uri"] for item in items)
        chain = separator.join(
            "{}({})".format(vi["class_name"], python_string_literal(u))
            for u in uris
        )
        header = "".join(dataset_header(u, version) for u in uris)
        return {
            "schedule_expr": "({})".format(chain),
            "sensor_tasks": [],
            "sensor_deps": [],
            "extra_imports": [vi["class_import"]],
            "max_active_runs": None,
            "header_docstring": header,
        }

    # DS-04 + D-11: heterogeneous-all
    dataset_uris = sorted(
        item["dataset"]["uri"] for item in items if "dataset" in item
    )
    non_datasets = [item for item in items if "dataset" not in item]

    # Schedule expression: alpha-sorted chain for datasets
    if not dataset_uris:
        schedule_expr = "None"
    elif len(dataset_uris) == 1:
        schedule_expr = "[{}({})]".format(
            vi["class_name"], python_string_literal(dataset_uris[0])
        )
    else:
        chain = separator.join(
            "{}({})".format(vi["class_name"], python_string_literal(u))
            for u in dataset_uris
        )
        schedule_expr = "({})".format(chain)

    # D-07: sort non-dataset items alphabetically by source kind
    non_datasets_sorted = sorted(non_datasets, key=_source_kind)

    # Recurse into render_single_trigger for each non-dataset source.
    # Pass empty roots — edges are wired explicitly below.
    all_sensor_tasks = []
    combined_imports = set()
    if dataset_uris:
        combined_imports.add(vi["class_import"])
    combined_header = ""

    for item in non_datasets_sorted:
        r = render_single_trigger(item, default_aws_conn_id, [], version)
        all_sensor_tasks.extend(r["sensor_tasks"])
        combined_imports.update(r["extra_imports"])
        if r["header_docstring"]:
            combined_header += r["header_docstring"]

    # D-10: _yard_join only when 2+ sensor tasks
    sensor_deps = []
    trigger_rule = "one_success" if "any" in trigger else "all_success"
    if len(all_sensor_tasks) >= 2:
        join_lines = [
            "    _yard_join = EmptyOperator(",
            '        task_id="_yard_join",',
            '        trigger_rule="{}",'.format(trigger_rule),
            "    )",
        ]
        all_sensor_tasks.append("\n".join(join_lines))
        combined_imports.add(vi["empty_op_import"])

        # Sensor -> _yard_join edges (alpha-sorted by emission order)
        for item in non_datasets_sorted:
            sensor_id = None
            if "s3" in item:
                sensor_id = "_yard_wait_s3"
            elif "sqs" in item:
                sensor_id = "_yard_wait_sqs"
            if sensor_id:
                sensor_deps.append("{} >> _yard_join".format(sensor_id))

        # _yard_join -> root edges
        for r in roots:
            sensor_deps.append("_yard_join >> {}".format(python_var_name(r)))

    elif len(all_sensor_tasks) == 1:
        # Single sensor: connect directly to roots, no _yard_join
        sensor_id = "_yard_wait_unknown"
        for item in non_datasets_sorted:
            if "s3" in item:
                sensor_id = "_yard_wait_s3"
                break
            elif "sqs" in item:
                sensor_id = "_yard_wait_sqs"
                break
        for r in roots:
            sensor_deps.append(
                "{} >> {}".format(sensor_id, python_var_name(r))
            )

    return {
        "schedule_expr": schedule_expr,
        "sensor_tasks": all_sensor_tasks,
        "sensor_deps": sensor_deps,
        "extra_imports": sorted(combined_imports),
        "max_active_runs": None,
        "header_docstring": combined_header,
    }


def render_trigger(trigger, schedule, default_aws_conn_id, roots, version):
    """Render a trigger configuration into codegen fragments.

    Single entry point for ALL schedule-expression resolution (D-03).
    Normalizes single-element composites, dispatches to single/composite
    renderers, applies CONC-01 max_active_runs default, and prepends
    version banner for triggered DAGs.
    """
    # D-12: normalize single-element composites to bare-single
    normalized = None
    if trigger is not None:
        if isinstance(trigger, dict):
            if (
                "all" in trigger
                and isinstance(trigger["all"], list)
                and len(trigger["all"]) == 1
            ):
                normalized = trigger["all"][0]
            elif (
                "any" in trigger
                and isinstance(trigger["any"], list)
                and len(trigger["any"]) == 1
            ):
                normalized = trigger["any"][0]
            elif "all" not in trigger and "any" not in trigger:
                # Already a single source
                normalized = trigger

    if normalized is not None:
        result = render_single_trigger(
            normalized, default_aws_conn_id, roots, version
        )
    elif trigger is not None:
        result = render_composite_trigger(
            trigger, default_aws_conn_id, roots, version
        )
    else:
        # No trigger — use top-level schedule literal or None
        result = {
            "schedule_expr": (
                python_string_literal(schedule) if schedule else "None"
            ),
            "sensor_tasks": [],
            "sensor_deps": [],
            "extra_imports": [],
            "max_active_runs": None,
            "header_docstring": "",
        }

    # CONC-01: default max_active_runs=1 for triggered DAGs
    if trigger is not None and result["max_active_runs"] is None:
        result["max_active_runs"] = 1

    # D-12: prepend VERSION_BANNER for triggered DAGs only
    if trigger is not None:
        banner = VERSION_BANNERS[version]
        if result["header_docstring"]:
            result["header_docstring"] = banner + "\n" + result["header_docstring"]
        else:
            result["header_docstring"] = banner

    return result


# ---------------------------------------------------------------------------
# DAG generation (ported from generation.rs)
# ---------------------------------------------------------------------------


def render_dag(job_name, job_config):
    """Main codegen entry point: render a complete Airflow DAG Python file.

    Supports schedule-only DAGs, all 6 trigger types, and version-aware output.
    """
    # D-06: default airflow version is 3
    version = job_config.get("airflow_version", 3)
    if version not in VERSION_IMPORTS:
        raise ValueError(
            "unsupported airflow_version={!r} (must be 2 or 3)".format(version)
        )
    vi = VERSION_IMPORTS[version]

    schedule = job_config.get("schedule")
    trigger = job_config.get("trigger")
    tasks = job_config.get("tasks", [])

    # Compute roots: task IDs with no depends_on entries (D-05)
    all_task_ids = {t.get("task_id", "") for t in tasks}
    roots = []
    for task in tasks:
        tid = task.get("task_id", "")
        depends_on = task.get("depends_on", [])
        if not depends_on:
            roots.append(tid)
        for dep in depends_on:
            if dep not in all_task_ids:
                raise ValueError(
                    "task '{}' depends_on unknown task '{}'".format(tid, dep)
                )

    # Resolve default_aws_conn_id from config (D-12)
    default_aws_conn_id = job_config.get("aws_conn_id")
    if not default_aws_conn_id:
        assume_role = job_config.get("assume_role")
        if assume_role:
            # Derive connection from role ARN (simplified for plugin)
            default_aws_conn_id = "yard_" + sanitize_identifier(assume_role)
        else:
            default_aws_conn_id = None

    # D-03: ALL schedule-expression resolution lives inside render_trigger
    trender = render_trigger(
        trigger, schedule, default_aws_conn_id, roots, version
    )
    schedule_expr = trender["schedule_expr"]

    # Determine which operator imports are needed
    needs_bash = False
    needs_glue = False
    has_publishes = False
    for task in tasks:
        tt = task.get("task_type", "")
        if tt == "bash":
            needs_bash = True
        elif tt == "glue":
            needs_glue = True
        if task.get("publishes"):
            has_publishes = True

    import_lines = []
    if needs_bash:
        import_lines.append(vi["bash_op_import"])
    if needs_glue:
        import_lines.append(
            "from airflow.providers.amazon.aws.operators.glue import GlueJobOperator"
        )
    if has_publishes:
        import_lines.append(vi["class_import"])

    # Merge trigger-derived imports with task-derived imports (deduplicated, sorted)
    combined_imports = sorted(
        set(import_lines) | set(trender["extra_imports"])
    )
    imports_block = "\n".join(combined_imports)

    # Render default_args
    default_args = render_default_args(job_config)

    # CONC-01 + user-override-wins: user max_active_runs always wins over
    # trigger auto-default. When both are None (schedule-only), emit nothing.
    effective_max_active = job_config.get("max_active_runs")
    if effective_max_active is None:
        effective_max_active = trender["max_active_runs"]
    if effective_max_active is not None:
        max_active_runs_block = "    max_active_runs={},\n".format(
            effective_max_active
        )
    else:
        max_active_runs_block = ""

    # Render tasks: prepend sensor tasks before user tasks
    task_lines = list(trender["sensor_tasks"])
    for task in tasks:
        tid = task.get("task_id", "")
        task_lines.append(render_task(tid, task, version))
    tasks_block = "\n".join(task_lines)

    # Dependency wiring: prepend sensor deps before user deps
    dep_lines = list(trender["sensor_deps"])
    for task in tasks:
        tid = task.get("task_id", "")
        depends_on = task.get("depends_on", [])
        for upstream in depends_on:
            dep_lines.append(
                "{} >> {}".format(
                    python_var_name(upstream), python_var_name(tid)
                )
            )

    if dep_lines:
        deps_block = "\n".join(dep_lines)
    else:
        deps_block = "# No task dependencies"

    # Trigger header block (version banner + per-source caveats)
    trigger_header_block = trender["header_docstring"]

    # Required connections block -- empty for now (Plan 3)
    required_connections_block = ""

    # Render via Jinja2
    env = Environment()
    template = env.from_string(DAG_TEMPLATE)
    return template.render(
        dag_name=job_name,
        trigger_header_block=trigger_header_block,
        required_connections_block=required_connections_block,
        imports_block=imports_block,
        default_args=default_args,
        schedule=schedule_expr,
        max_active_runs_block=max_active_runs_block,
        tasks_block=tasks_block,
        deps_block=deps_block,
    )


# ---------------------------------------------------------------------------
# Protocol handlers
# ---------------------------------------------------------------------------


def handle_validate(job_name, job_config):
    """Validate DAG configuration. Returns {'errors': [...]}."""
    errors = []

    # Rule: dags_bucket is required (D-10)
    dags_bucket = job_config.get("dags_bucket", "")
    if not dags_bucket:
        errors.append({
            "field": "dags_bucket",
            "message": "dags_bucket is required",
            "severity": "error",
        })

    # Rule: trigger and schedule mutual exclusion
    has_schedule = bool(job_config.get("schedule"))
    has_trigger = job_config.get("trigger") is not None
    if has_schedule and has_trigger:
        trigger = job_config["trigger"]
        # A schedule-type trigger inside trigger: is allowed with schedule field
        if not (isinstance(trigger, dict) and "schedule" in trigger):
            errors.append({
                "field": "trigger",
                "message": "trigger and schedule are mutually exclusive",
                "severity": "error",
            })

    # Rule: airflow_version must be 2 or 3 if present
    av = job_config.get("airflow_version")
    if av is not None and av not in (2, 3):
        errors.append({
            "field": "airflow_version",
            "message": "airflow_version must be 2 or 3",
            "severity": "error",
        })

    # Rule: trigger structure validation (T-05-02)
    trigger = job_config.get("trigger")
    if trigger is not None and isinstance(trigger, dict):
        recognized_keys = {"schedule", "dataset", "s3", "sqs", "api", "all", "any"}
        trigger_keys = set(trigger.keys()) & recognized_keys
        if not trigger_keys:
            errors.append({
                "field": "trigger",
                "message": (
                    "trigger must have one recognized key: "
                    "schedule, dataset, s3, sqs, api, all, or any"
                ),
                "severity": "error",
            })

        # S3 trigger: bucket must be non-empty
        if "s3" in trigger:
            s3 = trigger["s3"]
            if isinstance(s3, dict):
                bucket = s3.get("bucket", "")
                if not bucket:
                    errors.append({
                        "field": "trigger.s3.bucket",
                        "message": "S3 trigger bucket must be non-empty",
                        "severity": "error",
                    })

        # SQS trigger: queue_url must be non-empty
        if "sqs" in trigger:
            sqs = trigger["sqs"]
            if isinstance(sqs, dict):
                queue_url = sqs.get("queue_url", "")
                if not queue_url:
                    errors.append({
                        "field": "trigger.sqs.queue_url",
                        "message": "SQS trigger queue_url must be non-empty",
                        "severity": "error",
                    })

        # Composite triggers: items must be a non-empty list
        for comp_key in ("all", "any"):
            if comp_key in trigger:
                items = trigger[comp_key]
                if not isinstance(items, list) or len(items) == 0:
                    errors.append({
                        "field": "trigger.{}".format(comp_key),
                        "message": "composite trigger items must be a non-empty list",
                        "severity": "error",
                    })
                elif isinstance(items, list):
                    # Recurse into composite items for source-level validation
                    for idx, item in enumerate(items):
                        if not isinstance(item, dict):
                            continue
                        if "schedule" in item:
                            errors.append({
                                "field": "trigger.{}.{}".format(comp_key, idx),
                                "message": (
                                    "schedule source is not supported inside composite triggers; "
                                    "use a top-level schedule or trigger, not both"
                                ),
                                "severity": "error",
                            })
                        if "s3" in item:
                            s3 = item["s3"]
                            if isinstance(s3, dict) and not s3.get("bucket", ""):
                                errors.append({
                                    "field": "trigger.{}.{}.s3.bucket".format(comp_key, idx),
                                    "message": "S3 trigger bucket must be non-empty",
                                    "severity": "error",
                                })
                        if "sqs" in item:
                            sqs = item["sqs"]
                            if isinstance(sqs, dict) and not sqs.get("queue_url", ""):
                                errors.append({
                                    "field": "trigger.{}.{}.sqs.queue_url".format(comp_key, idx),
                                    "message": "SQS trigger queue_url must be non-empty",
                                    "severity": "error",
                                })
                    # Reject duplicate non-dataset source types (would produce
                    # duplicate Airflow task IDs that Airflow rejects at parse time)
                    source_types = [_source_kind(item) for item in items if isinstance(item, dict)]
                    non_dataset = [s for s in source_types if s and s != "dataset"]
                    if len(non_dataset) != len(set(non_dataset)):
                        errors.append({
                            "field": "trigger.{}".format(comp_key),
                            "message": "composite trigger cannot have duplicate non-dataset source types",
                            "severity": "error",
                        })

    # Rule: connection_id syntax validation (D-11)
    tasks = job_config.get("tasks", [])
    for task in tasks:
        conn_id = task.get("aws_conn_id") or task.get("connection_id")
        if conn_id is not None and (not isinstance(conn_id, str) or not conn_id.strip()):
            errors.append({
                "field": "connection_id",
                "message": "connection_id must be a non-empty string",
                "severity": "error",
            })

    return {"errors": errors}


def handle_codegen(job_name, job_config):
    """Generate an Airflow DAG Python file. Returns {'script': '...'}."""
    script = render_dag(job_name, job_config)
    return {"script": script}


# ---------------------------------------------------------------------------
# S3 helpers (ported from yard-plugin-common/src/aws/s3.rs -- S3ScriptOps)
# boto3 is imported lazily inside each function so that validate, codegen,
# and schema operations work in environments without boto3 installed.
# ---------------------------------------------------------------------------


def parse_s3_uri(uri):
    """Parse ``s3://bucket/key`` into a ``(bucket, key)`` tuple.

    Raises ``ValueError`` if *uri* does not start with ``s3://``.
    """
    if not uri.startswith("s3://"):
        raise ValueError("not an S3 URI: {}".format(uri))
    without_scheme = uri[len("s3://"):]
    slash = without_scheme.find("/")
    if slash < 0:
        raise ValueError("S3 URI missing key component: {}".format(uri))
    return without_scheme[:slash], without_scheme[slash + 1:]


def upload_dag(bucket, dag_id, content, prefix=""):
    """Upload DAG file content to S3 and return the ``s3://`` URI.

    Key construction mirrors ``S3ScriptOps::script_key`` from
    ``yard-plugin-common/src/aws/s3.rs``:
    - empty prefix  -> ``{dag_id}.py``
    - prefix ends ``/`` -> ``{prefix}{dag_id}.py``
    - otherwise     -> ``{prefix}/{dag_id}.py``

    T-05-01: *dag_id* is sanitized before use in the S3 key.
    """
    import boto3  # noqa: lazy import -- keep module-level free of boto3

    safe_id = sanitize_identifier(dag_id)

    if not prefix:
        key = "{}.py".format(safe_id)
    elif prefix.endswith("/"):
        key = "{}{}.py".format(prefix, safe_id)
    else:
        key = "{}/{}.py".format(prefix, safe_id)

    s3 = boto3.client("s3")
    s3.put_object(
        Bucket=bucket,
        Key=key,
        Body=content.encode("utf-8"),
        ContentType="text/x-python",
    )
    return "s3://{}/{}".format(bucket, key)


def delete_dag(bucket, key):
    """Delete a DAG file from S3."""
    import boto3  # noqa: lazy import

    s3 = boto3.client("s3")
    s3.delete_object(Bucket=bucket, Key=key)


def dag_exists(bucket, key):
    """Check whether a DAG file exists on S3 via ``HeadObject``.

    Returns ``True`` if the object exists, ``False`` on a 404 response.
    Re-raises any other ``ClientError``.
    """
    import boto3  # noqa: lazy import
    from botocore.exceptions import ClientError

    s3 = boto3.client("s3")
    try:
        s3.head_object(Bucket=bucket, Key=key)
        return True
    except ClientError as exc:
        code = exc.response.get("Error", {}).get("Code", "")
        if code == "404":
            return False
        raise


# ---------------------------------------------------------------------------
# Deploy / Destroy / Verify handlers
# ---------------------------------------------------------------------------


def handle_deploy(job_name, job_config, artifact):
    """Deploy a DAG file to S3 (D-10).

    Uploads the generated DAG script to ``s3://{dags_bucket}/...`` and returns
    a resource list containing the ``s3_object`` entry. Unlike the Glue plugin
    there is no service resource to create -- the DAG file on S3 IS the
    deployment.
    """
    dags_bucket = job_config.get("dags_bucket", "")
    dags_prefix = job_config.get("dags_prefix", "")

    log.info("uploading DAG %s to s3://%s/...", job_name, dags_bucket)

    s3_uri = upload_dag(dags_bucket, job_name, artifact, dags_prefix)

    return {
        "resources": [
            {"type": "s3_object", "id": s3_uri, "provider": "airflow"},
        ],
    }


def handle_destroy(job_name, resources):
    """Destroy DAG file(s) from S3 (D-10).

    Iterates the resource list and deletes each ``s3_object`` entry.
    Unparseable URIs are logged as warnings and skipped (non-fatal, matching
    the Glue plugin pattern from handler.rs).
    """
    for resource in resources:
        if resource.get("type") != "s3_object":
            continue
        try:
            bucket, key = parse_s3_uri(resource["id"])
        except (ValueError, KeyError) as exc:
            log.warning("skipping unparseable S3 resource: %s", exc)
            continue
        log.info("deleting DAG %s from s3://%s/%s", job_name, bucket, key)
        delete_dag(bucket, key)

    return {}


def handle_verify(job_name, resources):
    """Verify DAG file existence on S3 via HeadObject (D-10).

    For each ``s3_object`` resource, checks whether the S3 object exists.
    Unknown resource types default to ``exists=True`` (matching reference
    VerifyResponse pattern).
    """
    statuses = []
    for resource in resources:
        if resource.get("type") == "s3_object":
            try:
                bucket, key = parse_s3_uri(resource["id"])
                exists = dag_exists(bucket, key)
            except (ValueError, KeyError) as exc:
                log.warning("skipping unparseable S3 resource: %s", exc)
                exists = False
            statuses.append({"resource": resource, "exists": exists})
        else:
            # Unknown resource types assumed to exist
            statuses.append({"resource": resource, "exists": True})

    return {"statuses": statuses}


def handle_schema():
    """Return config field descriptors for the Airflow plugin."""
    return {
        "fields": [
            {
                "name": "dags_bucket",
                "field_type": "string",
                "required": True,
                "description": "S3 bucket for DAG file uploads",
            },
            {
                "name": "schedule",
                "field_type": "string",
                "required": False,
                "description": "Cron schedule expression",
            },
            {
                "name": "airflow_version",
                "field_type": "integer",
                "required": False,
                "description": "Airflow major version: 2 or 3, default 3",
            },
            {
                "name": "owner",
                "field_type": "string",
                "required": False,
                "description": "DAG owner",
            },
            {
                "name": "retries",
                "field_type": "integer",
                "required": False,
                "description": "Default task retries",
            },
            {
                "name": "max_active_runs",
                "field_type": "integer",
                "required": False,
                "description": "Maximum concurrent DAG runs",
            },
        ],
        "supported_source_types": None,
        "supported_sink_types": None,
    }


# ---------------------------------------------------------------------------
# Dispatch
# ---------------------------------------------------------------------------


def dispatch(request):
    """Route request to the appropriate handler by operation."""
    op = request.get("operation")
    if op == "validate":
        return handle_validate(request["job_name"], request["job_config"])
    elif op == "codegen":
        return handle_codegen(request["job_name"], request["job_config"])
    elif op == "deploy":
        return handle_deploy(
            request["job_name"], request["job_config"], request["artifact"]
        )
    elif op == "destroy":
        return handle_destroy(request["job_name"], request["resources"])
    elif op == "verify":
        return handle_verify(request["job_name"], request["resources"])
    elif op == "schema":
        return handle_schema()
    else:
        raise ValueError("unknown operation: {}".format(op))


# ---------------------------------------------------------------------------
# Protocol entry point (mirrors PluginServer::run from server.rs)
# ---------------------------------------------------------------------------


def main():
    """Protocol lifecycle: handshake -> read request -> dispatch -> respond -> exit."""
    try:
        # Step 1: Write handshake to stdout
        handshake = {
            "protocol_version": PROTOCOL_VERSION,
            "name": PLUGIN_NAME,
            "version": PLUGIN_VERSION,
            "capabilities": [
                "validate",
                "codegen",
                "deploy",
                "destroy",
                "verify",
                "schema",
            ],
        }
        sys.stdout.write(json.dumps(handshake) + "\n")
        sys.stdout.flush()

        # Step 2: Read request from stdin
        line = sys.stdin.readline()
        if not line.strip():
            log.error("no request received on stdin")
            sys.exit(1)

        request = json.loads(line.strip())

        # Step 3: Dispatch and write response
        response = dispatch(request)
        sys.stdout.write(json.dumps(response) + "\n")
        sys.stdout.flush()
        sys.exit(0)

    except Exception as exc:
        log.error("%s", exc)
        # Write error response to stdout before exiting, matching Rust SDK behavior
        error_response = {"error": str(exc)}
        sys.stdout.write(json.dumps(error_response) + "\n")
        sys.stdout.flush()
        sys.exit(1)


if __name__ == "__main__":
    main()
